services:
  backend:
    build:
      context: ./API
      dockerfile: backend.dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./spec-trackr-app
      dockerfile: frontend.dockerfile
    container_name: react_frontend
    ports:
      - "3002:80"
    restart: unless-stopped
