services:
  spec-trackr:
    build: 
      context: ./frontend/spec-trackr-app
      dockerfile: sta.dockerfile
    ports:
      - "3001:3001"  # 고정 포트 매핑
    networks:
      - spec-net

  spectrackr-main:
    build: 
      context: ./frontend/spectrackr-main
      dockerfile: main.dockerfile
    ports:
      - "3003:3003"  # 고정 포트 매핑
    networks:
      - spec-net
    depends_on:
      - spec-trackr

networks:
  spec-net:
    driver: bridge